<a href="https://colab.research.google.com/github/vaishnavigirase0817/Agentic-Housing-Navigator/blob/main/P_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data ={
    "study_hours":[1,2,3,4,5,6,7,8,9,10],
    "attendance":[26,45,67,66,79,89,56,45,34,67],
    "marks":[34,54,66,27,89,78,89,56,76,88]
}
df=pd.DataFrame(data)
print(df)

   study_hours  attendance  marks
0            1          26     34
1            2          45     54
2            3          67     66
3            4          66     27
4            5          79     89
5            6          89     78
6            7          56     89
7            8          45     56
8            9          34     76
9           10          67     88

In [ ]:
print('First five rows:')
df.head()

First five rows:

   study_hours  attendance  marks
0            1          26     34
1            2          45     54
2            3          67     66
3            4          66     27
4            5          79     89

In [ ]:
print('shape of Dataset:')
df.shape

shape of Dataset:

(10, 3)

In [ ]:
df.describe()

       study_hours  attendance      marks
count     10.00000   10.000000  10.000000
mean       5.50000   57.400000  65.700000
std        3.02765   19.906448  22.544031
min        1.00000   26.000000  27.000000
25%        3.25000   45.000000  54.500000
50%        5.50000   61.000000  71.000000
75%        7.75000   67.000000  85.500000
max       10.00000   89.000000  89.000000

In [ ]:
print('Statistical Analusis:\n',df.describe()),

Statistical Analusis:
        study_hours  attendance      marks
count     10.00000   10.000000  10.000000
mean       5.50000   57.400000  65.700000
std        3.02765   19.906448  22.544031
min        1.00000   26.000000  27.000000
25%        3.25000   45.000000  54.500000
50%        5.50000   61.000000  71.000000
75%        7.75000   67.000000  85.500000
max       10.00000   89.000000  89.000000

(None,)

In [ ]:
print('check for nut values:')
df.isnull().sum()

check for nut values:

study_hours    0
attendance     0
marks          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()

   study_hours  attendance  marks
0            1          26     34
1            2          45     54
2            3          67     66
3            4          66     27
4            5          79     89
5            6          89     78
6            7          56     89
7            8          45     56
8            9          34     76
9           10          67     88

In [ ]:
import seaborn as sns
df_corr= df.corr()
plt.figure(figsize=(6,4))